name: Checks

on: [pull_request, push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Check
        run: yarn check

      - name: Lint
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: yarn build

      - name: Build vxrn
        run: cd packages/vxrn && yarn build
      - name: Test
        run: yarn test
      - name: Notify Discord on failure
        if: failure()
        run: |
          echo "Tests failed, sending message to Discord..."
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$(echo '{}' | jq --arg content "🚨 Tests failed for commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) in [${{ github.repository }}](https://github.com/${{ github.repository }})." \
              --arg url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
              '{ "embeds": [ { "title": $content, "url": $url, "color": 15158332 } ] }')" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

